### ISSUE TITLE
Reduce grayness

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/summit.haxe.org#4]
The current design depresses me because it's so gray-in-gray. We should make it look more haxey with some orange and such.

Assigning this to Mark in hopes that he can work some CSS magic.

**Comment by Simn** [comment]
I've done a bit of a redesign after a friend gave me some input. I like how it looks now, but the CSS needs some cleanup. Also because it doesn't look quite right on mobile yet.

Any takers?

**Comment by ibilon** [comment]
Looks nice :+1:
I'll take care of the mobile fixes (#3)

**Comment by Simn** [comment]
Right I had already forgotten that I opened an issue for that... so I guess we can close this one.
